image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DOCKER_TLS_CERTDIR: ""
  DATABASE_URL: 'mongod'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  image: docker:20.10.2
  services:
    - docker:20.10.2-dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - echo 'Building reddit app..'
    - docker build -t $REGISTRY_USER/reddit:${CI_COMMIT_SHORT_SHA} ./reddit
    - docker push $REGISTRY_USER/reddit:${CI_COMMIT_SHORT_SHA}
  only:
    - branches
  except:
    - master

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

deploy_reddit_app:
  stage: review
  tags:
    - shell
  before_script: []
  script:
    - docker network create reddit || true
    - docker kill $(docker ps --filter name=reddit-* -aq) || true
    - docker rm $(docker ps --filter name=reddit-* -aq) || true
    - docker run -d --name reddit-mongo --network=reddit --network-alias=mongod mongo:latest
    - docker run -d --name reddit-app --network=reddit --env DATABASE_URL=mongod -p 9292:9292 $REGISTRY_USER/reddit:5da306d8
  environment:
    name: reddit-test/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
